export const products = [
  {
    id: 1,
    name: "Gamburger",
    title: "Burger bulochkasi, tuzlangan bodring, pomidor, go'shtli...",
    price: 25000,
    img: "/img/gamburger.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Chizburger",
    title: "Burger bulochkasi, tuzlangan bodring, pomidor, go'shtli...",
    price: 28000,
    img: "/img/chizburger.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Bigburger",
    title: "Burger bulochkasi, tuzlangan bodring, pomidor, 2 ta go'...",
    price: 40000,
    img: "/img/bigburger.png",
    quantity: 1,
  },
  {
    id: 4,
    name: "Hot Dog",
    title: "Hot-dog bulochkasi, Kanada sosiskasi, tuzlangan bodring...",
    price: 12000,
    img: "/img/hotdog.png",
    quantity: 1,
  },
  {
    id: 5,
    name: "Chiz dog",
    title: "Hot-dog bulochkasi, kanada sosiskasi, tuzlangan bodri...",
    price: 15000,
    img: "/img/chizdog.png",
    quantity: 1,
  },
  {
    id: 6,
    name: "Longer",
    title: "Hot-dog bulochka,ketchup, mayonez, strips 1 dona, tuzl...",
    price: 15000,
    img: "/img/longer.png",
    quantity: 1,
  },
  {
    id: 7,
    name: "German Donar",
    title: "Non, ranch sousi, qizil karam salati, Doner go'shti, ay...",
    price: 30000,
    img: "/img/germandonar.png",
    quantity: 1,
  },
  {
    id: 8,
    name: "Shaurma",
    title: "Donor bulochka, mol go'shti-donar, yangi bodring, pomid...",
    price: 28000,
    img: "/img/shaurma.png",
    quantity: 1,
  },
  {
    id: 9,
    name: "Moxito",
    title: "",
    price: 15000,
    img: "/img/moxito.png",
    quantity: 1,
  },
  {
    id: 10,
    name: "Sharbat Dena",
    title: "",
    price: 5000,
    img: "/img/sharbatdena.png",
    quantity: 1,
  },
  {
    id: 11,
    name: "Fuse tea",
    title: "",
    price: 10000,
    img: "/img/fusetea.png",
    quantity: 1,
  },
  {
    id: 12,
    name: "Bonaqua",
    title: "",
    price: 5000,
    img: "/img/suv.png",
    quantity: 1,
  },
];
